--liquibase formatted sql
--changeset rgrzegorczyk:create_APP_VERSION_LOGS stripComments:false context:liquibase_project_start labels:liquibase_project_start
--comment Table to insert information about  start and end of version deployment
--rollback DROP TABLE APP_VERSION_LOGS PURGE;
--------------------------------------------------------
--  DDL for Table APP_VERSION_LOGS
--------------------------------------------------------
CREATE TABLE APP_VERSION_LOGS 
 (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
LOG_CODE VARCHAR2(50 CHAR), 
VERSION_NAME VARCHAR2(50 CHAR), 
SCRIPT_NAME VARCHAR2(50 CHAR), 
INSTALL_DATE DATE DEFAULT sysdate
 ) ;
 COMMENT ON COLUMN APP_VERSION_LOGS.ID IS 'ID - primary key';
 COMMENT ON COLUMN APP_VERSION_LOGS.LOG_CODE IS 'Event/ log code - VERSION_START / VERSION_END ';
 COMMENT ON COLUMN APP_VERSION_LOGS.VERSION_NAME IS 'Version name';
 COMMENT ON COLUMN APP_VERSION_LOGS.SCRIPT_NAME IS 'Script name';
 COMMENT ON COLUMN APP_VERSION_LOGS.INSTALL_DATE IS 'Date of deployment';

--------------------------------------------------------
--  Constraints for Table APP_VERSION_LOGS
--------------------------------------------------------
ALTER TABLE APP_VERSION_LOGS ADD CONSTRAINT APP_VERSION_LOGS_PK PRIMARY KEY (ID);
