--liquibase formatted sql
--changeset liquibase:CONFERENCES runOnChange:false context:liquibase_project_start labels:liquibase_project_start
--comment initial changeset for CONFERENCES
--rollback SELECT 1 FROM DUAL
--------------------------------------------------------
--  DDL for Table CONFERENCES
--------------------------------------------------------

  CREATE TABLE "LB_VERSION_CONTROL_PERFECTION"."CONFERENCES" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255), 
	"DESCRIPTION" VARCHAR2(255), 
	"COUNTRY_ID" CHAR(2), 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE
   ) ;

--------------------------------------------------------
--  Constraints for Table CONFERENCES
--------------------------------------------------------

  ALTER TABLE "LB_VERSION_CONTROL_PERFECTION"."CONFERENCES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LB_VERSION_CONTROL_PERFECTION"."CONFERENCES" ADD CONSTRAINT "CONFERENCES_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

--changeset rgrzegorczyk:add_col_UNIVERSE_ID stripComments:false context:version_2  labels:jira_task_2 
--comment Added column UNIVERSE_ID 
--rollback ALTER TABLE CONFERENCES DROP UNIVERSE_ID;
ALTER TABLE CONFERENCES ADD (UNIVERSE_ID NUMBER);   


