--liquibase formatted sql
--changeset liquibase:UNIVERSES runOnChange:false context:liquibase_project_start labels:liquibase_project_start
--comment initial changeset for UNIVERSES
--rollback SELECT 1 FROM DUAL
--------------------------------------------------------
--  DDL for Table UNIVERSES
--------------------------------------------------------

  CREATE TABLE "LB_VERSION_CONTROL_PERFECTION"."UNIVERSES" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"UNIVERSE_NAME" VARCHAR2(40)
   ) ;

   COMMENT ON COLUMN "LB_VERSION_CONTROL_PERFECTION"."UNIVERSES"."ID" IS 'Primary key of universe_id table.';
   COMMENT ON COLUMN "LB_VERSION_CONTROL_PERFECTION"."UNIVERSES"."UNIVERSE_NAME" IS 'universe_id name';
   COMMENT ON TABLE "LB_VERSION_CONTROL_PERFECTION"."UNIVERSES"  IS 'UNIVERESES table.';

--------------------------------------------------------
--  Constraints for Table UNIVERSES
--------------------------------------------------------

  ALTER TABLE "LB_VERSION_CONTROL_PERFECTION"."UNIVERSES" MODIFY ("ID" NOT NULL ENABLE);




